# Generated by Django 4.0.4 on 2024-09-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Warranty_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
