# Generated by Django 4.0.4 on 2024-09-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_alter_product_warranty_period_alter_product_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
