# Generated by Django 4.0.4 on 2024-09-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_alter_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
