# Generated by Django 4.0.4 on 2024-09-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_product_is_suggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
