# Generated by Django 4.2.16 on 2024-10-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0006_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product_color', to='app_store.product'),
        ),
    ]
