# Generated by Django 4.2.16 on 2024-10-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0009_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
