# Generated by Django 4.2.16 on 2025-01-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0010_alter_color_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
