# Generated by Django 4.0.4 on 2024-09-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0005_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
