# Generated by Django 4.0.4 on 2024-09-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0006_alter_point_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_point', to='app_social.comment'),
        ),
    ]
