# Generated by Django 4.0.4 on 2024-09-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0008_alter_point_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='description',
        ),
        migrations.RemoveField(
            model_name='point',
            name='type',
        ),
        migrations.AddField(
            model_name='point',
            name='strength',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='weakness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
