# Generated by Django 4.0.4 on 2024-09-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0009_remove_point_description_remove_point_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='point',
            name='weakness',
        ),
        migrations.CreateModel(
            name='CommentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(blank=True, max_length=255, null=True)),
                ('weakness', models.CharField(blank=True, max_length=255, null=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='app_social.point')),
            ],
        ),
    ]
