# Generated by Django 4.0.4 on 2024-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0010_remove_point_strength_remove_point_weakness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='strength',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='weakness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CommentPoint',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
