# Generated by Django 4.0.4 on 2024-09-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0011_remove_point_comment_comment_strength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='strength',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='weakness',
            field=models.TextField(blank=True, null=True),
        ),
    ]
