# Generated by Django 4.2.16 on 2024-10-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0013_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isusefull',
            name='is_useful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
