# Generated by Django 4.2.16 on 2024-10-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0014_alter_isusefull_is_useful'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
